using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _00030Demo_Features
{
   //FILE 1
    public partial class Demo
    {
        partial void Test(string name);

        public Demo()
        {
            Test("cdac");
        }
    }

    //AutoGenerated Code : Pls Do Not modify this!
    public partial class Emp
    {
        private int _No;
        private string _Name;

        partial void Validate(string propertyName, object propertyValue);

        public string Name
        {
            get { return _Name; }
            set 
            {
                Validate("Name", value);
                _Name = value; 
            }
        }

        public int No
        {
            get { return _No; }
            set 
            {
                Validate("No", value);
                _No = value; 
            }
        }

    }
}
